/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/auth/LoginView': RouteRecordInfo<'/auth/LoginView', '/auth/LoginView', Record<never, never>, Record<never, never>>,
    '/auth/RegisterView': RouteRecordInfo<'/auth/RegisterView', '/auth/RegisterView', Record<never, never>, Record<never, never>>,
    '/ChatBoardView': RouteRecordInfo<'/ChatBoardView', '/ChatBoardView', Record<never, never>, Record<never, never>>,
    '/LoginView': RouteRecordInfo<'/LoginView', '/LoginView', Record<never, never>, Record<never, never>>,
  }
}
